module.exports = [
    "Auch gibt es niemanden, der den Schmerz an sich liebt, sucht oder wünscht, nur, weil er Schmerz ist, es sei denn, es kommt zu zufälligen Umständen, in denen Mühen und Schmerz ihm große Freude bereiten können.",
    "Achtung! Dieser Blindtext wird gerade durch 130 Millionen Rezeptoren Ihrer Netzhaut erfaßt. Die Zellen werden dadurch in einen Erregungszustand versetzt, der sich über den Sehnerv in dem hinteren Teil Ihres Gehirns ausbreitet. Von dort aus überträgt sich die Erregung in Sekundenbruchteilen auch in andere Bereiche Ihres Großhirns. Ihr Stirnlappen wird stimuliert. Von dort aus gehen jetzt Willensimpulse aus, die Ihr zentrales Nervensystem in konkrete Handlungen umsetzt. Kopf und Augen reagieren bereits. Sie folgen dem Text, nehmen die darin enthaltenen Informationen auf wie ein Schwamm. Nicht auszudenken, was mit Ihnen hätte passieren können, wenn dieser Blindtext durch einen echten Text ersetzt worden wäre.",
    "Nein, meine Texte les ich nicht, so nicht, stöhnte Oxmox. Er war mit Franklin, Rockwell und dem halbtaxgrauen Panther Weidemann in Memphis (Heartbreak Hotel) zugange. Sie warteten auf die fette Gill, um bei der Bank of Helvetica die Kapitälchen in Kapital umzuwandeln. Oxmox ließ nicht locker. Ich fleh euch an, rettet meine Copy, gebt meinem Body nochn Durchschuß! Kein Problem, erbarmte sich Old Face Baskerville, streichelte seinen Hund, zog seine einspaltige Poppl, legte an und traf! (Zeidank nichts Ernstes – nurn bißchen Fraktur.) Oxmox: Danke, ist jetzt mit Abstand besser. Derweil jumpte der Fox leise over the Buhl, die sich mal wieder immerdar wie jedes Jahr gesellte.",
    "Diesmal war Guaredisch ihr Erwählter, weil seine Laufweite einem vollgetankten Bodoni entsprach und seine ungezügelte Unterlänge ihre Serifen so serafisch streifte, daß sie trotz Techtelmechtelei die magere Futura, jene zuverlässige und gern eingesetzte Langstreckenläuferin, rechtsbündig überholen konnten. Leute, giftelte Tiffany, macht endlich maln Punkt. Und das Komma soll sich gefällixt an die richtige Stelle setzen. Und keine Trennungen. Und nicht zu viele Anschläge heut nacht! Die Goudy war vorbei. Aus einem üblen Geviert tauchte eine Horde Gemeiner auf, angeführt von einem Versalen. Als sie des Grauwerts anblickig wurden, machten sie auf dem Absatz kehrt — ohne Einzug. Die in der letzten Reihe warfen noch schnell eine Handvoll Buchstaben in die Luft.",
    "Ich habe diesen Text nur als Blindtext für die Setzerei Appel in Hamburg geschrieben. Wenn ich gewußt hätte, daß Sie diese Zeilen lesen (man stelle sich das mal vor: Sie persönlich lesen das hier!), dann hätte ich mir natürlich mehr Mühe gegeben. Immerhin bin ich gelernter Texter und seit über 20 Jahren am Üben — da hätte ich wahrlich was Besseres schreiben können als diesen Stuß. Was sollen Sie jetzt von mir denken? Bisher haben Sie Konstantin Jacoby vielleicht für einen ganz ordentlichen Kreativen gehalten — und dann das hier! Ehrlich gesagt: Ich weiß auch nicht, wie mir das passieren konnte. Eine Worthülse nach der anderen! Buchstabe an Buchstabe — Inhalt aber gleich Null. Vermutlich geben Sie mir nie einen Auftrag, nachdem Sie das hier gelesen haben — da kann ich soviel Goldmedaillen haben, wie ich will. Dies ist der Beweis: Jacoby kann’s einfach nicht, Schluß aus! Zu meiner Entschuldigung kann ich nur sagen: Ich habe diesen Text nur als Blindtext für die Setzerei Appel in Hamburg geschrieben.",
    "Wenn ich gewußt hätte, daß Sie diese Zeilen lesen (man stelle sich das mal vor: Sie persönlich lesen das hier!), dann hätte ich mir natürlich mehr Mühe gegeben. Immerhin bin ich gelernter Texter und seit über 20 Jahren am Üben — da hätte ich wahrlich was Besseres schreiben können als diesen Stuß. Was sollen Sie jetzt von mir denken? Bisher haben Sie Konstantin Jacoby vielleicht für einen ganz ordentlichen Kreativen gehalten — und dann das hier! Ehrlich gesagt: Ich weiß auch nicht, wie mir das passieren konnte. Eine Worthülse nach der anderen! Buchstabe an Buchstabe — Inhalt aber gleich Null. Vermutlich geben Sie mir nie einen Auftrag, nachdem Sie das hier gelesen haben — da kann ich soviel Goldmedaillen haben, wie ich will. Dies ist der Beweis: Jacoby kann’s einfach nicht, Schluß aus! Zu meiner Entschuldigung kann ich nur sagen: Ich habe diesen Text nur als Blindtext für die Setzerei Appel in Hamburg geschrieben.",
    "Überall dieselbe alte Leier. Das Layout ist fertig, der Text lässt auf sich warten. Damit das Layout nun nicht nackt im Raume steht und sich klein und leer vorkommt, springe ich ein: der Blindtext. Genau zu diesem Zwecke erschaffen, immer im Schatten meines großen Bruders »Lorem Ipsum«, freue ich mich jedes Mal, wenn Sie ein paar Zeilen lesen. Denn esse est percipi - Sein ist wahrgenommen werden.",
    "Und weil Sie nun schon die Güte haben, mich ein paar weitere Sätze lang zu begleiten, möchte ich diese Gelegenheit nutzen, Ihnen nicht nur als Lückenfüller zu dienen, sondern auf etwas hinzuweisen, das es ebenso verdient wahrgenommen zu werden: Webstandards nämlich.",
    "Standards sparen Zeit bei den Entwicklungskosten und sorgen dafür, dass sich Webseiten später leichter pflegen lassen. Natürlich nur dann, wenn sich alle an diese Standards halten. Das gilt für Browser wie Firefox, Opera, Safari und den Internet Explorer ebenso wie für die Darstellung in Handys.",
    "Lorem iPad dolor sit amet, consectetur Apple adipisicing elit, sed do eiusmod incididunt ut labore et dolore magna aliqua Shenzhen. Ut enim ad minim veniam, quis nostrud no multi-tasking ullamco laboris nisi ut aliquip iPad ex ea commodo consequat. Duis aute irure dolor iPad in reprehenderit in voluptate velit esse CEO Steve Jobs dolore eu fugiat nulla pariatur. Windows 7 ha ha ha. Excepteur sint occaecat battery life non proident, iPad in culpa qui officia deserunt mollit anim id est laborum.",
    "Vor einigen Jahren wurden vier Männer einer militärischen Spezialeinheit wegen eines Verbrechens verurteilt, das sie nicht begangen haben. Sie brachen aus dem Gefängnis aus und tauchten in Los Angeles unter. Seitdem werden sie von der Militärpolizei gejagt, aber sie helfen anderen die in Not sind. Sie wollen nicht so ganz ernst genommen werden, aber ihre Gegner müssen sie ernst nehmen. Also wenn sie einmal ein Problem haben und nicht mehr weiter wissen suchen sie doch Das A-Team."
]